spring:
  profiles:
    active:
    - test
---
server:
  port: 83ss00
spring:
  application:
    name: train-edu-userInfo-service---111111111
  profiles: dev

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8550/eureka/
    enabled: true
  instance:
    instance-id: userInfoService
    prefer-ip-address: true
    
---
server:
  port: 8200
spring:
  application:
    name: train-edu-userInfo-service--222222222222222
  profiles: test

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8550/eureka/
    enabled: true
  instance:
    instance-id: userInfoService
    prefer-ip-address: true
